### ISSUE TITLE
Jar created on Ubuntu is not working in CentOS

### ISSUE THREAD

**Issue by heflinstephenraj** [levyfan/sentencepiece-jni#27]
I have created the Linux jar on an ubuntu machine. Then I moved the ubuntu jar to a CentOS machine and tried to tokenise a text. It threw me an error.
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/libsentencepiece_jni4849969498159746745.so: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /tmp/libsentencepiece_jni4849969498159746745.so)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
        at java.lang.Runtime.load0(Runtime.java:810)
        at java.lang.System.load(System.java:1088)
        at com.github.google.sentencepiece.SentencePieceJNI.<clinit>(SentencePieceJNI.java:9)
        at com.github.google.sentencepiece.SentencePieceProcessor.<init>(SentencePieceProcessor.java:13)
```
I cloned the sentencepiece-jni repo in the centos machine and created a jar. Then I replaced the ubuntu jar with the newly created centos jar and run the code. It worked.
I have attached the ubuntu Jar file and the centos jar file for your reference.
https://drive.google.com/drive/folders/1ubpmParRAoMIs5Zj0Ehah9Sd_BBwgyEm?usp=sharing

**Ubuntu OS details**
```
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

```
**CentOS details**
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
Please help out @levyfan  @erip 
Thanks in advance.

**Comment by heflinstephenraj** [comment]
@erip Thanks for your response. 
But I am able to use the CentOS jar on ubuntu. Could you please tell me how?
